# Generated by Django 5.0.14 on 2026-07-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Store', max_length=255)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('primary_color', models.CharField(default='#000000', help_text='Hex color, e.g. #1a1a1a', max_length=7)),
                ('secondary_color', models.CharField(default='#ffffff', help_text='Hex color, e.g. #ffffff', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
