# Generated by Django 5.0.14 on 2026-07-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_attribute_attributevalue_product_productimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, choices=[('', 'None'), ('hot', 'Hot'), ('new', 'New'), ('sale', 'Sale')], default='', max_length=10),
        ),
    ]
